cmake_minimum_required(VERSION 3.22)
project(android_loading_host_check LANGUAGES C CXX)
set(DOCOCR_SOURCE_ROOT "/home/dr/project/docprase")
set(DOCOCR_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(DOCOCR_REQUIRE_MNN ON CACHE BOOL "" FORCE)
set(DOCOCR_REQUIRE_LLM ON CACHE BOOL "" FORCE)
set(DOCOCR_MNN_ROOT "/home/dr/project/MNN" CACHE PATH "" FORCE)
set(DOCOCR_MNN_INCLUDE "/home/dr/project/MNN/include" CACHE PATH "" FORCE)
set(DOCOCR_LLM_INCLUDE "/home/dr/project/MNN/transformers/llm/engine/include" CACHE PATH "" FORCE)
set(DOCOCR_MNN_LIBRARY "/home/dr/project/MNN/build/libMNN.so" CACHE FILEPATH "" FORCE)
set(DOCOCR_LLM_LIBRARY "/home/dr/project/MNN/build/libllm.so" CACHE FILEPATH "" FORCE)
add_subdirectory("${DOCOCR_SOURCE_ROOT}" docprase)
include("/home/dr/project/android_ocr/app/src/main/cpp/android_engine_sources.cmake")
