import React,{memo,useEffect,useState,useRef}from'react';
import{Streamdown,defaultRehypePlugins}from'streamdown';
import{createMathPlugin}from'@streamdown/math';
import{cjk}from'@streamdown/cjk';
import{displayPrefix}from'../prototypes/ocr-streaming/stream-state.mjs';
const plugins={math:createMathPlugin({singleDollarTextMath:true}),cjk};
const [harden]=defaultRehypePlugins.harden;
const rehype=[defaultRehypePlugins.raw,defaultRehypePlugins.sanitize,[harden,{defaultOrigin:'https://ocr.local/',allowedImagePrefixes:['https://ocr.local/assets/'],allowedLinkPrefixes:[],allowDataImages:false}]];
const transform=url=>{const s=url.replace(/^https:\/\/ocr\.local\//,'');return s.startsWith('assets/')&&!s.split('/').includes('..')?s:'';};
export function ImageResource({asset,name,openImage}){const[status,setStatus]=useState('loading'),[attempt,setAttempt]=useState(0),imageRef=useRef();useEffect(()=>{const img=imageRef.current;setStatus(!asset?.src?'error':img?.complete?(img.naturalWidth>0?'loaded':'error'):'loading');},[asset?.src,attempt]);return <span className="image-frame" data-resource={name} style={{aspectRatio:`${asset?.width||400}/${asset?.height||240}`,maxWidth:asset?.width||'100%'}}>{status!=='loaded'&&<span className="image-placeholder">{status==='error'?<>图片资源缺失或加载失败<button onClick={()=>setAttempt(a=>a+1)}>重试</button><small>JSON 请连同 assets 打包成 ZIP 导入</small></>:'加载图片…'}</span>}{asset?.src&&<img ref={imageRef} key={attempt} src={asset.src} alt="文档插图" style={{opacity:status==='loaded'?1:0}} onLoad={()=>setStatus('loaded')} onError={()=>setStatus('error')} onClick={()=>openImage(asset.src)}/>}<button className="expand-image" disabled={status!=='loaded'} onClick={()=>openImage(asset.src)}>放大</button></span>;}
export const Region=memo(function Region({block,components,edit}){const atomic=['table','formula'].includes(block.type);const text=atomic&&!block.done?'':displayPrefix(block.raw,block.done);return <section className="region" data-region={block.id} data-done={block.done}><div className="region-debug">{block.id} · {block.type} · {block.done?'完成':'接收中'}</div>{text?<Streamdown plugins={plugins} components={components} controls={false} animated={false} isAnimating={!block.done} urlTransform={transform} rehypePlugins={rehype} className="markdown">{text}</Streamdown>:<div className="region-pending">正在接收{block.type==='table'?'表格':block.type==='formula'?'公式':'内容'}…</div>}{!block.done&&<span className="receiving">正在生成 · {block.count} 字符</span>}{block.sourceStatus!=='ok'&&block.sourceStatus!=='notice'&&<span className="warning">{block.sourceStatus==='pending-layout'?'页面已保留 · 待版面分析':block.sourceStatus==='pending-ocr'?'图片已保留 · 图片文字待 OCR':'原始识别结果待核对'}</span>}{block.done&&edit&&<button className="edit-region" onClick={()=>edit(block)}>校对</button>}</section>;});
