import{chromium}from'playwright';
import assert from'node:assert/strict';
import{mkdir,readFile,writeFile,rm}from'node:fs/promises';
import{spawn}from'node:child_process';
import{unzipSync,strFromU8}from'fflate';
const out='web/test-results';await mkdir(out,{recursive:true});await rm(`${out}/failure.txt`,{force:true});await rm(`${out}/report.json`,{force:true});
const port=4184;const server=spawn('python3',['-m','http.server',String(port),'--bind','127.0.0.1','--directory','web/dist'],{stdio:'ignore'});const origin=`http://127.0.0.1:${port}`;
const results=[],errors=[],requests=[];let browser;
try{
 for(let n=0;n<50;n++){try{if((await fetch(origin)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||'/home/dr/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome',args:['--no-sandbox']});
 const context=await browser.newContext({viewport:{width:412,height:892},acceptDownloads:true});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith(origin))requests.push(r.url());});
 const check=async(name,fn)=>{await fn();results.push({name,passed:true});console.log('PASS',name);};
 await page.goto(origin);await page.waitForSelector('.sample-card');
 await check('首页保留拍照、导入和 JSON 入口',async()=>{assert(await page.getByRole('button',{name:'拍照',exact:true}).isVisible());assert(await page.getByRole('button',{name:'导入文件',exact:true}).isVisible());await page.screenshot({path:`${out}/home.png`});});
 await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByLabel('JSON 回放每次字符数',{exact:true}).selectOption('64');await page.getByRole('dialog').getByRole('button',{name:'关闭',exact:true}).click();
 await page.getByRole('button',{name:'文字 / 表格 / 图片',exact:true}).click();
 await check('真实 JSON 完成 16 个区域，图片和表格渲染',async()=>{await page.getByRole('button',{name:'重新回放',exact:true}).waitFor({timeout:45000});assert.equal(await page.locator('.region').count(),16);assert(await page.locator('.markdown table').count()>0);assert.equal(await page.locator('.image-frame img').count(),4);await page.waitForFunction(()=>[...document.querySelectorAll('.image-frame img')].every(i=>i.complete&&i.naturalWidth>0&&i.style.opacity==='1'));});
 await check('竖屏内容不会撑宽页面',async()=>{assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.locator('.reader').evaluate(e=>e.scrollTop=0);await page.screenshot({path:`${out}/portrait.png`});});
 await check('已完成区域保持 DOM 身份；上翻不被新输出拉走',async()=>{await page.getByRole('button',{name:'重新回放'}).click();await page.waitForSelector('.region[data-done="true"]');await page.evaluate(()=>window.committed=document.querySelector('.region[data-done="true"]'));await page.locator('.reader').hover();await page.mouse.wheel(0,-1500);const y=await page.locator('.reader').evaluate(e=>e.scrollTop);await page.waitForTimeout(900);assert(await page.evaluate(()=>window.committed===document.querySelector('.region[data-done="true"]')));assert.equal(await page.locator('.reader').evaluate(e=>e.scrollTop),y);await page.getByRole('button',{name:'暂停输出'}).click();});
 await check('暂停停止增量并可继续',async()=>{const text=await page.locator('.reader').innerText();await page.waitForTimeout(350);assert.equal(await page.locator('.reader').innerText(),text);await page.getByRole('button',{name:'继续输出'}).click();await page.getByRole('button',{name:'重新回放'}).waitFor({timeout:45000});});
 await check('横屏显示原文和结果，图片可缩放查看',async()=>{await page.setViewportSize({width:1000,height:650});await page.waitForTimeout(300);assert(await page.locator('aside.source').isVisible());await page.locator('.reader').evaluate(e=>e.scrollTop=0);await page.screenshot({path:`${out}/landscape.png`});await page.getByRole('button',{name:'原图',exact:true}).click();await page.locator('.image-dialog[open]').waitFor();await page.getByRole('button',{name:'＋',exact:true}).click();assert.equal(await page.locator('.viewer-body img').evaluate(e=>e.style.width),'150%');await page.locator('.image-dialog').getByRole('button',{name:'关闭',exact:true}).click();});
 await check('校对内容保存，导出 Markdown 包含修改',async()=>{await page.locator('.edit-region').first().click();await page.getByRole('textbox',{name:'校对 Markdown'}).fill('## 已校对标题\n\n中文内容修订测试。');await page.getByRole('button',{name:'保存修改'}).click();await page.getByRole('button',{name:'导出 / 分享'}).click();const p=page.waitForEvent('download');await page.getByRole('button',{name:'Markdown 单文件'}).click();const d=await p;assert((await readFile(await d.path(),'utf8')).startsWith('## 已校对标题'));});
 let bundle;
 await check('ZIP 导出包含图片、JSON 和校对状态',async()=>{await page.getByRole('button',{name:'导出 / 分享'}).click();const p=page.waitForEvent('download');await page.getByRole('button',{name:'完整文档 ZIP（含图片）',exact:true}).click();const d=await p;bundle=await d.path();assert((await readFile(bundle)).length>10000);});
 await check('历史在刷新后保留进度与校对内容',async()=>{await page.getByRole('button',{name:'返回首页'}).click();await page.reload();await page.getByRole('button',{name:'最近记录'}).click();await page.locator('.history-row>button').first().click();await page.getByText('已校对标题',{exact:true}).waitFor();assert.equal(await page.locator('.region').count(),16);});
 await check('ZIP 再导入保留校对和图片，刷新后图片可用',async()=>{await page.getByRole('button',{name:'返回首页'}).click();const p=page.waitForEvent('filechooser');await page.getByRole('button',{name:'导入文件',exact:true}).click();await(await p).setFiles({name:'roundtrip.zip',mimeType:'application/zip',buffer:await readFile(bundle)});await page.getByRole('button',{name:'重新回放'}).waitFor({timeout:45000});assert(await page.getByText('已校对标题',{exact:true}).isVisible());await page.getByRole('button',{name:'返回首页'}).click();await page.reload();await page.getByRole('button',{name:'最近记录'}).click();await page.locator('.history-row>button').first().click();await page.waitForFunction(()=>[...document.querySelectorAll('.image-frame img')].length===4&&[...document.querySelectorAll('.image-frame img')].every(i=>i.complete&&i.naturalWidth>0&&i.style.opacity==='1'));});
 await check('仅测试模式显示处理详情',async()=>{assert.equal(await page.locator('.diagnostics').count(),0);await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByRole('checkbox',{name:/测试模式/}).click();await page.getByRole('dialog').getByRole('button',{name:'关闭',exact:true}).click();assert.equal(await page.locator('.diagnostics').count(),1);});
 await check('模型页列出版面、Ovis 和 GLM-OCR 三个 ModelScope 仓库',async()=>{await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByRole('button',{name:/识别模型/}).click();assert(await page.getByText('dr3334/PP-DocLayoutV3-mnn',{exact:true}).isVisible());assert(await page.getByText('dr3334/ovrics-ocrv2_mnn',{exact:true}).isVisible());assert(await page.getByText('MNN/GLM-OCR-MNN',{exact:true}).isVisible());await page.screenshot({path:`${out}/models.png`});await page.getByRole('dialog').getByRole('button',{name:'关闭',exact:true}).click();});
 await page.getByRole('button',{name:'返回首页'}).click();await page.setViewportSize({width:412,height:892});
 await check('公式样本完整输出，KaTeX 已渲染',async()=>{await page.getByRole('button',{name:'公式 / 图片',exact:true}).click();await page.getByRole('button',{name:'重新回放'}).waitFor({timeout:45000});assert.equal(await page.locator('.region').count(),10);assert(await page.locator('.katex').count()>=5);await page.locator('.reader').evaluate(e=>e.scrollTop=e.scrollHeight);await page.screenshot({path:`${out}/formulas.png`});});
 await check('缺失图片展示固定占位并可重试',async()=>{await page.getByRole('button',{name:'返回首页'}).click();const p=page.waitForEvent('filechooser');await page.getByRole('button',{name:'导入文件',exact:true}).click();await(await p).setFiles('prototypes/ocr-streaming/fixtures/odb-13/document.json');await page.getByRole('button',{name:'重新回放'}).waitFor({timeout:45000});const img=page.locator('.image-frame').first();const height=await img.evaluate(e=>e.getBoundingClientRect().height);await img.getByRole('button',{name:'重试'}).click();assert.equal(await img.evaluate(e=>e.getBoundingClientRect().height),height);});
 for(const [name,title,colspan] of [['sales-with-image.xlsx','图片附件',3],['slides-with-table-and-image.pptx','第 2 张幻灯片',2]]){
  await check(`Office 原生解析结果回放：${name}`,async()=>{
   await page.getByRole('button',{name:'返回首页'}).click();const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'导入文件',exact:true}).click();await(await chooser).setFiles(`verification/office-fixtures/${name}.zip`);
   await page.getByRole('button',{name:'重新回放'}).waitFor({timeout:45000});assert.equal(await page.locator('.status select option').count(),2);assert.equal(await page.locator(`.markdown td[colspan="${colspan}"]`).count(),1);
   await page.getByRole('combobox',{name:'文档章节'}).selectOption({label:title});await page.waitForFunction(()=>[...document.querySelectorAll('.image-frame img')].some(i=>i.style.opacity==='1'&&i.naturalWidth>0));assert.equal(await page.locator('.image-frame').count(),1);
   assert(await page.getByText('图片已保留 · 图片文字待 OCR',{exact:true}).isVisible());assert(await page.getByText('— 内容已提取 · 图片文字待 OCR —',{exact:true}).isVisible());assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:`${out}/${name}.png`});
  });
 }
 await check('Office 回放导出的 JSON 保留幻灯片边界和图片状态',async()=>{
  await page.getByRole('button',{name:'导出 / 分享'}).click();const pending=page.waitForEvent('download');await page.getByRole('button',{name:'完整文档 ZIP（含图片）',exact:true}).click();const download=await pending;const files=unzipSync(new Uint8Array(await readFile(await download.path())));const ir=JSON.parse(strFromU8(files['document.json']));assert.equal(ir.pages.length,2);assert.equal(ir.pages[1].title,'第 2 张幻灯片');const image=ir.pages[1].blocks.find(b=>b.type==='image');assert.equal(image.status,'pending-ocr');assert(files[image.content.resource]);
 });
 await check('原生大表格按区域直接显示，不逐字等待',async()=>{
  await page.getByRole('button',{name:'返回首页'}).click();await page.locator('.sample-card').waitFor();
  await page.evaluate(async()=>{await new Promise((resolve,reject)=>{const open=indexedDB.open('suishou-ocr-v1',1);open.onerror=()=>reject(open.error);open.onsuccess=()=>{const db=open.result,tx=db.transaction('documents','readwrite'),store=tx.objectStore('documents'),all=store.getAll();all.onsuccess=()=>{const d=all.result.sort((a,b)=>b.updatedAt-a.updatedAt)[0];d.mode='native-parse';d.title='原生表格速度验收';d.updatedAt=Date.now()+1000;d.progress=0;d.anchor=null;d.status='ready';const table=d.blocks.find(b=>b.type==='table');table.markdown='<table>'+Array.from({length:1000},(_,i)=>'<tr><td>原生大表格</td><td>'+i+'</td></tr>').join('')+'</table>';store.put(d);};tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>reject(tx.error);};});localStorage.setItem('ocr-settings',JSON.stringify({chunk:3,wifiOnly:true}));});
  await page.reload();await page.getByRole('button',{name:'最近记录'}).click();await page.getByRole('button',{name:/^原生表格速度验收/}).click();const start=Date.now();await page.getByRole('button',{name:'继续输出'}).click();await page.getByRole('button',{name:'重新回放'}).waitFor({timeout:8000});assert(Date.now()-start<8000);assert.equal(await page.locator('.markdown table tr').count(),1000);
 });
 await check('离线渲染无第三方请求和未捕获异常',async()=>{assert.deepEqual(requests,[]);assert.deepEqual(errors,[]);});
 await context.close();await writeFile(`${out}/report.json`,JSON.stringify({passed:results.length,results,errors,externalRequests:requests},null,2));
}catch(e){await writeFile(`${out}/failure.txt`,String(e.stack));throw e;}finally{if(browser)await browser.close();server.kill();}
