import{chromium}from'playwright';import assert from'node:assert/strict';import{readFile,writeFile}from'node:fs/promises';import{spawn}from'node:child_process';import{unzipSync,strFromU8}from'fflate';
const port=4195,origin=`http://127.0.0.1:${port}`,server=spawn('python3',['-m','http.server',String(port),'--bind','127.0.0.1','--directory','web/dist'],{stdio:'ignore'});let browser;const results=[];
try{
 for(let i=0;i<40;i++){try{if((await fetch(origin)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||'/home/dr/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome',args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:412,height:892},acceptDownloads:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(origin);await page.locator('.sample-card').waitFor();
 const ir={pages:[{page_id:'p1',reading_order:['a','b','c'],blocks:[{id:'a',type:'text',content:{text:'甲段'}},{id:'b',type:'text',content:{text:'乙段'}},{id:'c',type:'text',content:{text:'尾段内容'.repeat(100)}}]}],resources:[]};
 const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'导入文件',exact:true}).click();await(await chooser).setFiles({name:'移动验收.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(ir))});
 await page.waitForFunction(()=>document.querySelectorAll('.region[data-done="true"]').length===2);await page.getByRole('button',{name:'调整顺序',exact:true}).click();assert.equal(await page.locator('.order-row').count(),2);assert(await page.getByRole('button',{name:'上移区域 1',exact:true}).isDisabled());assert(await page.getByRole('button',{name:'下移区域 2',exact:true}).isDisabled());await page.getByRole('button',{name:'下移区域 1',exact:true}).click();await page.getByRole('button',{name:'保存顺序',exact:true}).click();await page.getByText('区域顺序已保存，导出将使用新顺序').waitFor();assert.equal(await page.locator('.region').first().getAttribute('data-region'),'p1-b');results.push('输出中调整已完成区域，边界按钮受限，保存后显示顺序正确');
 await page.getByRole('button',{name:'继续输出',exact:true}).click();await page.getByRole('button',{name:'重新回放',exact:true}).waitFor({timeout:20000});assert.deepEqual(await page.locator('.region').evaluateAll(es=>es.map(e=>e.dataset.region)),['p1-b','p1-a','p1-c']);results.push('继续输出无重复、遗漏或尾部错位');
 await page.getByRole('button',{name:'调整顺序',exact:true}).click();await page.getByRole('button',{name:'下移区域 1',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'关闭',exact:true}).click();assert.equal(await page.locator('.region').first().getAttribute('data-region'),'p1-b');results.push('关闭调整面板不应用未保存的顺序');
 await page.getByRole('button',{name:'返回首页',exact:true}).click();await page.reload();await page.getByRole('button',{name:'最近记录',exact:true}).click();await page.locator('.history-row>button').first().click();assert.equal(await page.locator('.region').first().getAttribute('data-region'),'p1-b');results.push('历史记录与刷新保留新顺序');
 await page.getByRole('button',{name:'导出 / 分享',exact:true}).click();let pending=page.waitForEvent('download');await page.getByRole('button',{name:'Markdown 单文件',exact:true}).click();let dl=await pending;assert((await readFile(await dl.path(),'utf8')).startsWith('乙段\n\n甲段'));results.push('Markdown 导出使用调整后的顺序');
 await page.getByRole('button',{name:'导出 / 分享',exact:true}).click();pending=page.waitForEvent('download');await page.getByRole('button',{name:'完整文档 ZIP（含图片）',exact:true}).click();dl=await pending;const bundle=await readFile(await dl.path()),files=unzipSync(bundle),output=JSON.parse(strFromU8(files['document.json']));assert.deepEqual(output.pages[0].reading_order,['p1-b','p1-a','p1-c']);results.push('ZIP 的 DocumentIR reading_order 使用新顺序');
 await page.getByRole('button',{name:'返回首页',exact:true}).click();const pick=page.waitForEvent('filechooser');await page.getByRole('button',{name:'导入文件',exact:true}).click();await(await pick).setFiles({name:'reimport.zip',mimeType:'application/zip',buffer:bundle});await page.locator('.region').first().waitFor();assert.equal(await page.locator('.region').first().getAttribute('data-region'),'p1-b');assert.deepEqual(errors,[]);results.push('ZIP 重新导入保持顺序，无页面错误');await writeFile('verification/reorder-ui.json',JSON.stringify({passed:results.length,results},null,2));console.log(results.join('\n'));
}finally{await browser?.close();server.kill();}
